
image:
- Visual Studio 2017
- Ubuntu
before_build:
  # Display .NET Core version
  - dotnet --version
  - dotnet restore
build_script:
  - dotnet build
before_test:
  - bash scripts/restore.sh
test_script:
  - dotnet test