
image:
- Ubuntu
- Visual Studio 2017
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - sh: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - sh: dotnet --version
  - sh: dotnet restore
build_script:
  - sh: dotnet build
before_test:
  - sh: bash scripts/restore.sh
test_script:
  - sh: dotnet test