
image:
- Ubuntu
- Visual Studio 2017
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - dotnet --version
  - dotnet restore
build_script:
  - dotnet build
before_test:
  - bash scripts/restore.sh
test_script:
  - dotnet test