
image:
- Visual Studio 2017
- Ubuntu
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - dotnet --version
  - dotnet restore
build_script:
  - dotnet build
before_test:
  - cmd: mkdir C:\Program Files\dotnet\shared\assembly # workaround of https://github.com/Microsoft/visualfsharp/issues/6161
  - dotnet restore sample/EmptyProject/EmptyProject.fsproj
  - dotnet restore sample/MainProject/MainProject.fsproj
  - dotnet restore sample/HasLocalDll/HasLocalDll.fsproj
  - dotnet restore sample/FSharpKoans.Core/FSharpKoans.Core.fsproj
  - dotnet restore sample/HasTests/HasTests.fsproj
  - dotnet restore sample/ReferenceCSharp/ReferenceCSharp.fsproj
  - dotnet restore sample/ReferenceCSharp.AssemblyName/ReferenceCSharp.AssemblyName.fsproj
  - dotnet restore sample/Signature/Signature.fsproj
  - dotnet restore sample/HasPackageReference/HasPackageReference.fsproj
  - dotnet build sample/CSharpProject/CSharpProject.csproj
  - dotnet build sample/CSharpProject.AssemblyName/CSharpProject.AssemblyName.csproj
  - dotnet build sample/SlnReferences/ReferencedProject.fsproj
test_script:
  - dotnet test