
image:
- Visual Studio 2017
- Ubuntu
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  - cmd: dotnet restore
build_script:
  - cmd: dotnet build
before_test:
  - cmd: bash scripts/restore.sh
test_script:
  - cmd: dotnet test