version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2-sdk

    steps:
      - checkout
      - run:
          name: Restore test projects
          command: bash scripts/restore.sh
      - run: 
          name: Build all
          command: dotnet build
      - run: 
          name: Test LSP.Tests
          command: dotnet test tests/LSP.Tests
      - run: 
          name: Test ProjectCracker.Tests
          command: dotnet test tests/ProjectCracker.Tests
      - run: 
          name: Test FSharpLanguageServer.Tests
          command: dotnet test tests/FSharpLanguageServer.Tests
